use_frameworks!

platform :ios, '10.0'

target 'YDPlayer_Example' do
  pod 'YDPlayer', :path => '../'
  pod 'SnapKit'
  pod 'Kingfisher'
  target 'YDPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
